name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Cloud Provider
      env:
        CLOUD_AUTH_TOKEN: ${{ secrets.CLOUD_AUTH_TOKEN }}
      run: |
        source venv/bin/activate
